global:
  scrape_interval: 15s  # Default scrape interval
  evaluation_interval: 15s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Placeholder for other services
  - job_name: 'opt-db-app'
    static_configs:
      - targets: ['opt-db-app:3000']  # Replace with actual service endpoint
